apiVersion: v1
kind: deployment
metadata: 
  name: nginx-deployment
  namespace: dev-namespace
  labels:
    app: nginx-app
    environment: dev
    project: eksctl-cluster-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: dev
      component: web
      tier: frontend
      project: eksctl-cluster-development
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        environment: dev
        component: web
        tier: frontend
        project: eksctl-cluster-development
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80 
        env:
        # Method 1 — Hardcoded value
        - name: APP_ENV   
          value: "development"

        # Method 2 — From ConfigMap
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_PORT
              
        # Method 3 — From Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD  
    

