apiVersion: v1
kind: Pod
metadata:
  name: nginx-np-pod
  namespace: dev-namespace
  labels:
    app: nginx-np
    component: web
    tier: frontend
    environment: dev
    project: eksctl-cluster-development
spec:
  containers: 
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080