apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  namespace: dev-namespace
spec:
  selector:
    app: nginx-lb
    environment: dev
    component: web
    tier: frontend
    project: eksctl-cluster-development
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30080 #node port
  type: LoadBalancer  
