apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-1-dev
    instanceTypes:
      - t3.medium
      - m5.large
      - c5.large
      - t3.small
    desiredCapacity: 2
    spot: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub