apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-1-dev
    instanceType: t3.medium
    desiredCapacity: 2
    spot: true
    ssh:
      allow: true
      publicKeyName: eks-keyg