apiVersion: v1
kind: Namespace
metadata:
  name: dev-namespace
  labels:
    name: dev-namespace 
    environment: dev
    project: eksctl-cluster-development
  annotations:
    description: "This is the development namespace for the eksctl cluster"   
