apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: dev-namespace
  labels:
    app: secret-app
    environment: dev
    project: eksctl-cluster-development
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret