apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    environment: dev
    component: web
    tier: frontend
    project: eksctl-cluster-development
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080