apiVersion: v1
kind: Service
metadata:
  name: nginx-np-service
spec:
  selector:
    app: nginx
    environment: dev
    component: web
    tier: frontend
    project: eksctl-cluster-development
    purpose: nodeport-service
  ports:
    - protocol: TCP
      port: 80 # The port that the service will listen on
      targetPort: 80 # The port that the container is listening on
  type: NodePort
