apiVersion: v1
kind: Service
metadata:
  name: nginx-NP-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port that the service will listen on
      targetPort: 80 # The port that the container is listening on
  type: NodePort
  