apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    env: production
spec:
  selector:
    app: nginx        # matches pod labels above
    env: production   # matches pod labels above
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer